# Generated by Django 4.1 on 2022-08-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_alter_category_name_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=40),
        ),
    ]
