# Generated by Django 4.1 on 2022-08-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=72),
        ),
    ]
